databases:
- cluster_name: wallfair
  engine: MONGODB
  name: prod-mongo
  production: true
  version: "4"
- cluster_name: prod-redis
  engine: REDIS
  name: prod-redis
  production: true
  version: "6"
- cluster_name: prod-db
  engine: PG
  db_name: defaultdb
  db_user: doadmin
  name: prod-db
  production: true
  version: "13"
envs:
- key: REDIS_CONNECTION
  scope: RUN_AND_BUILD_TIME
  value: ${prod-redis.DATABASE_URL}
name: production-crash-game-backend
region: fra
services:
- envs:
  - key: JWT_KEY
    scope: RUN_TIME
    value: $JWT_KEY
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: PRODUCTIVE
  - key: POSTGRES_CA
    scope: RUN_AND_BUILD_TIME
    value: /usr/src/app/ssl/postgres-prod.crt
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: doadmin
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: prod-db-do-user-9290946-0.b.db.ondigitalocean.com
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: defaultdb
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: $POSTGRES_PASSWORD
  - key: POSTGRES_SSL
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: "25060"
  - key: DB_CONNECTION
    scope: RUN_AND_BUILD_TIME
    value: $MONGO_DB_URL
  http_port: 80
  image:
    registry_type: DOCR
    repository: crash-game-backend
    tag: $VERSION
  instance_count: 1
  instance_size_slug: professional-xs
  name: production-crash-game-backend
  routes:
  - path: /
  source_dir: /