apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-game
spec:
  template:
    spec:
      containers:
        - name: crash-game
          envFrom:
          - configMapRef:
              name: app-secrets
          - configMapRef:
              name: backend-production-values

