apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: playmoney
commonLabels:
  environment: playmoney

patches:
  - prodConfigPatch.yaml
  - resourcesPatch.yaml