apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-game
spec:
  template:
    spec:
      containers:
        - name: crash-game
          envFrom:
          - configMapRef:
              name: app-secrets
          - configMapRef:
              name: app-global-secrets
          - configMapRef:
              name: crash-game-config
          - configMapRef:
              name: postgres-conn
          - configMapRef:
              name: redis-conn
          - configMapRef:
              name: mongo-conn
