apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crash-game-ingress
spec:
  tls:
  - hosts:
    - elon-api.alpacasino.io
    secretName: crash-game-cert-secret
  rules:
  - host: elon-api.wallfair.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: crash-game-backend
              port:
                number: 80
