apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-game
  labels:
    app: crash-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-game
  template:
    metadata:
      labels:
        app: crash-game
    spec:
      containers:
        - image: registry.digitalocean.com/wallfair/crash-game-k8s
          imagePullPolicy: Always
          name: crash-game
          envFrom:
          - configMapRef:
              name: app-config
          - configMapRef:
              name: app-secrets
          - configMapRef:
              name: crash-game-config
          ports:
            - containerPort: 80


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: staging
  name: crash-game
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crash-game
  targetCPUUtilizationPercentage: 50

---

apiVersion: v1
kind: Service
metadata:
  name: crash-game-backend
  namespace: staging
spec:
  selector:
    app: crash-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
