apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-dump-game
  labels:
    app: pump-dump-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pump-dump-game
  template:
    metadata:
      labels:
        app: pump-dump-game
    spec:
      containers:
        - image: registry.digitalocean.com/wallfair/crash-game-k8s
          imagePullPolicy: Always
          name: pump-dump-game
          envFrom:
          - configMapRef:
              name: app-config
          - configMapRef:
              name: app-secrets
          - configMapRef:
              name: pump-dump-game-secrets
          - configMapRef:
              name: pump-dump-game-config
          - configMapRef:
              name: postgres-conn
          - configMapRef:
              name: mongo-conn
          - configMapRef:
              name: redis-conn
          ports:
            - containerPort: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: staging
  name: pump-dump-game
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pump-dump-game
  targetCPUUtilizationPercentage: 50